######################################################################
# Automatically generated by qmake (3.1) Fri Aug 7 13:56:56 2026
######################################################################

TEMPLATE = app
TARGET = "tic-tac-toe"
INCLUDEPATH += .
RESOURCES += resources.qrc

# You can make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# Please consult the documentation of the deprecated API in order to know
# how to port your code away from it.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_UP_TO=0x060000 # disables all APIs deprecated in Qt 6.0.0 and earlier
QT += quick
QT += multimedia

# Input
SOURCES += src/main.cpp \
           src/GameEngine.cpp \
           src/Board.cpp \
           src/AIEngine.cpp

HEADERS += src/GameEngine.hpp \
           src/Board.hpp \
           src/AIEngine.hpp